/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package art.gallery;

import javax.swing.JFrame;
import java.awt.*;

/**
 *
 * @author Tayba
 */
public class add_artwork extends javax.swing.JFrame {

    /**
     * Creates new form add_artwork
     */
    public add_artwork() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jLabelArtist = new javax.swing.JLabel();
        jLabelyear = new javax.swing.JLabel();
        jLabelCategory = new javax.swing.JLabel();
        jLabelprice = new javax.swing.JLabel();
        jLabelimage = new javax.swing.JLabel();
        title = new javax.swing.JTextField();
        artist = new javax.swing.JTextField();
        year = new javax.swing.JTextField();
        category = new javax.swing.JTextField();
        price = new javax.swing.JTextField();
        AddImage = new javax.swing.JButton();
        Addartwork = new javax.swing.JButton();
        Address = new javax.swing.JLabel();
        jLbl_Close = new javax.swing.JLabel();
        jLbl_minimize = new javax.swing.JLabel();
        jLbl_backGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        jLabelTitle.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitle.setText("Title of Artwork :");
        jPanel1.add(jLabelTitle);
        jLabelTitle.setBounds(60, 110, 150, 30);

        jLabelArtist.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelArtist.setForeground(new java.awt.Color(255, 255, 255));
        jLabelArtist.setText("The Artist :");
        jPanel1.add(jLabelArtist);
        jLabelArtist.setBounds(60, 150, 150, 30);

        jLabelyear.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelyear.setForeground(new java.awt.Color(255, 255, 255));
        jLabelyear.setText("The Year :");
        jPanel1.add(jLabelyear);
        jLabelyear.setBounds(60, 190, 150, 30);

        jLabelCategory.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelCategory.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCategory.setText("Category :");
        jPanel1.add(jLabelCategory);
        jLabelCategory.setBounds(60, 230, 150, 30);

        jLabelprice.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelprice.setForeground(new java.awt.Color(255, 255, 255));
        jLabelprice.setText("The Price :");
        jPanel1.add(jLabelprice);
        jLabelprice.setBounds(60, 270, 150, 30);

        jLabelimage.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelimage.setForeground(new java.awt.Color(255, 255, 255));
        jLabelimage.setText("Image :");
        jPanel1.add(jLabelimage);
        jLabelimage.setBounds(60, 310, 150, 30);

        title.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titleActionPerformed(evt);
            }
        });
        jPanel1.add(title);
        title.setBounds(220, 110, 250, 30);

        artist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                artistActionPerformed(evt);
            }
        });
        jPanel1.add(artist);
        artist.setBounds(220, 150, 250, 30);

        year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearActionPerformed(evt);
            }
        });
        jPanel1.add(year);
        year.setBounds(220, 190, 250, 30);

        category.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryActionPerformed(evt);
            }
        });
        jPanel1.add(category);
        category.setBounds(220, 230, 250, 30);

        price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceActionPerformed(evt);
            }
        });
        jPanel1.add(price);
        price.setBounds(220, 270, 250, 30);

        AddImage.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        AddImage.setText("Add Image");
        jPanel1.add(AddImage);
        AddImage.setBounds(230, 310, 140, 31);

        Addartwork.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Addartwork.setText("Add ArtWork");
        jPanel1.add(Addartwork);
        Addartwork.setBounds(190, 400, 220, 37);

        Address.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Address.setText("Add New ArtWork");
        jPanel1.add(Address);
        Address.setBounds(10, 0, 250, 60);

        jLbl_Close.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLbl_Close.setText("X");
        jLbl_Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLbl_CloseMouseClicked(evt);
            }
        });
        jPanel1.add(jLbl_Close);
        jLbl_Close.setBounds(560, 0, 30, 60);

        jLbl_minimize.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLbl_minimize.setText("_");
        jLbl_minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLbl_minimizeMouseClicked(evt);
            }
        });
        jPanel1.add(jLbl_minimize);
        jLbl_minimize.setBounds(520, 0, 23, 44);

        jLbl_backGround.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tayba\\Desktop\\photo\\56325218_385414615624966_9000357719730814976_n.jpg")); // NOI18N
        jPanel1.add(jLbl_backGround);
        jLbl_backGround.setBounds(0, -20, 600, 550);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void artistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_artistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_artistActionPerformed

    private void categoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoryActionPerformed

    private void priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceActionPerformed

    private void yearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearActionPerformed

    private void titleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titleActionPerformed

    private void jLbl_CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbl_CloseMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLbl_CloseMouseClicked

    private void jLbl_minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbl_minimizeMouseClicked
        // TODO add your handling code here:
         this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLbl_minimizeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(add_artwork.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(add_artwork.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(add_artwork.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(add_artwork.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new add_artwork().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddImage;
    private javax.swing.JButton Addartwork;
    private javax.swing.JLabel Address;
    private javax.swing.JTextField artist;
    private javax.swing.JTextField category;
    private javax.swing.JLabel jLabelArtist;
    private javax.swing.JLabel jLabelCategory;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelimage;
    private javax.swing.JLabel jLabelprice;
    private javax.swing.JLabel jLabelyear;
    private javax.swing.JLabel jLbl_Close;
    private javax.swing.JLabel jLbl_backGround;
    private javax.swing.JLabel jLbl_minimize;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField price;
    private javax.swing.JTextField title;
    private javax.swing.JTextField year;
    // End of variables declaration//GEN-END:variables
}
