/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package art.gallery;
import java.awt.*;
import javax.swing.*;

/**
 *
 * @author Tayba
 */
public class gallery extends javax.swing.JFrame {

    /**
     * Creates new form gallery
     */
    public gallery() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        AddNewArtwork = new javax.swing.JButton();
        DisplayCustomerInformation = new javax.swing.JButton();
        AddArtist = new javax.swing.JButton();
        UpdatePrice = new javax.swing.JButton();
        jLbl_Close = new javax.swing.JLabel();
        jLbl_minimize = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLbl_backGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        AddNewArtwork.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AddNewArtwork.setActionCommand(" Add new Artwork");
        AddNewArtwork.setLabel(" Add new Artwork");
        AddNewArtwork.setName(""); // NOI18N
        AddNewArtwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddNewArtworkActionPerformed(evt);
            }
        });
        jPanel1.add(AddNewArtwork);
        AddNewArtwork.setBounds(110, 80, 260, 30);

        DisplayCustomerInformation.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DisplayCustomerInformation.setText("Display customer information");
        DisplayCustomerInformation.setActionCommand(" Add new Artwork");
        DisplayCustomerInformation.setName(""); // NOI18N
        jPanel1.add(DisplayCustomerInformation);
        DisplayCustomerInformation.setBounds(110, 150, 260, 30);

        AddArtist.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AddArtist.setText(" Add Artist");
        AddArtist.setActionCommand(" Add new Artwork");
        AddArtist.setName(""); // NOI18N
        AddArtist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddArtistActionPerformed(evt);
            }
        });
        jPanel1.add(AddArtist);
        AddArtist.setBounds(110, 210, 260, 30);

        UpdatePrice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        UpdatePrice.setText("Update Price");
        UpdatePrice.setActionCommand(" Add new Artwork");
        UpdatePrice.setName(""); // NOI18N
        UpdatePrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdatePriceActionPerformed(evt);
            }
        });
        jPanel1.add(UpdatePrice);
        UpdatePrice.setBounds(110, 280, 260, 30);

        jLbl_Close.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLbl_Close.setText("X");
        jLbl_Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLbl_CloseMouseClicked(evt);
            }
        });
        jPanel1.add(jLbl_Close);
        jLbl_Close.setBounds(470, -20, 40, 110);

        jLbl_minimize.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLbl_minimize.setText("_");
        jLbl_minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLbl_minimizeMouseClicked(evt);
            }
        });
        jPanel1.add(jLbl_minimize);
        jLbl_minimize.setBounds(440, 10, 19, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 32)); // NOI18N
        jLabel3.setText("Gallery");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 0, 140, 50);

        jLbl_backGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/art/gallery/Art-Galleries-in-karachi.jpg"))); // NOI18N
        jPanel1.add(jLbl_backGround);
        jLbl_backGround.setBounds(-160, 0, 1210, 440);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddNewArtworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddNewArtworkActionPerformed
        // TODO add your handling code here:
        add_artwork a = new add_artwork ();
        a.setVisible(true);
        a.pack();
        a.setLocationRelativeTo(null);
        a.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_AddNewArtworkActionPerformed

    private void AddArtistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddArtistActionPerformed
        // TODO add your handling code here

        Add_Artist a = new Add_Artist();
        a.setVisible(true);
        a.pack();
        a.setLocationRelativeTo(null);
        a.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();

    }//GEN-LAST:event_AddArtistActionPerformed

    private void UpdatePriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdatePriceActionPerformed
        // TODO add your handling code here:
        Update_Price U = new Update_Price();
        U.setVisible(true);
        U.pack();
        U.setLocationRelativeTo(null);
        U.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        //UpdatePrice.setBackground(new Color(0,0,0,0));
    }//GEN-LAST:event_UpdatePriceActionPerformed

    private void jLbl_CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbl_CloseMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLbl_CloseMouseClicked

    private void jLbl_minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbl_minimizeMouseClicked
        // TODO add your handling code here:
                 this.setState(JFrame.ICONIFIED);

    }//GEN-LAST:event_jLbl_minimizeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gallery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gallery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gallery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gallery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gallery().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddArtist;
    private javax.swing.JButton AddNewArtwork;
    private javax.swing.JButton DisplayCustomerInformation;
    private javax.swing.JButton UpdatePrice;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLbl_Close;
    private javax.swing.JLabel jLbl_backGround;
    private javax.swing.JLabel jLbl_minimize;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
